name: Demo js tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 14
      uses: actions/setup-node@v3
      with:
        node-version: "14"
        cache: 'npm'
    - name: install Alure
      run: npm install -g allure-commandline --save-dev
    - name: Create a temp artifact folder
      run: |
        mkdir output
    - name: Install yarn
      run: yarn
    - name: Run tests
      run: yarn run test
    - name: Report
      if: always()
      run: allure generate -o allure-results
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: allure-results
        path: allure-results/
        retention-days: 10
